### ISSUE TITLE
Pip cannot get requirements to build package

### ISSUE THREAD

**Issue by Katongakitkat** [TomCatanach/TheRichmondRyders#15]
Added all the documentation that should be needed for packaging, and added a placeholder program to test the packaging,  however upon trying to install the package locally it is failing, stating:
  error: subprocess-exited-with-error
  
    × Getting requirements to build editable did not run successfully.
    │ exit code: 1
    ╰─> [48 lines of output]
Anybody got any ideas as to why it might not be working?

**Comment by AmritWalia13** [comment]
It might be to do with the version of Python. What is your pip command?

**Comment by Katongakitkat** [comment]
pip install -e /Users/jakereilly/TheRichmondRyders

**Comment by Katongakitkat** [comment]
Fixed, had to change a folder name and edit some called names within the files
