### ISSUE TITLE
Left to do

### ISSUE THREAD

**Issue by AmritWalia13** [TomCatanach/TheRichmondRyders#17]
What do we have left to do?  Are any issues coming up that we need to look at?

**Comment by Katongakitkat** [comment]
Once the final program is put together, some of the files used in the packaging process need to be updated.
- Requirements.txt needs to be updated with any packages used in the program.
- The program needs to be placed in src/schropy in place of placeholder.py
- Ideally could also do with writing scripts in command_line_interface.py to make the package useable from the command line. Said scripts can they also be listed in setup.cfg.
- Structure of package, plus description if files within package, could be added to README.md.
- If time, can also write code in Tests/tests.py that can be run to make sure program is still working as intended after any changes.

**Comment by TomCatanach** [comment]
I have pushed some more code that builds on the program as it is in my branch, only the first potential plotting function is currently anywhere near operational and would be laughable to actually call it as such. Suffice to say I am having great difficulty getting the program to accept the potential functions that I give it, infact at this stage with idential inputs the program will output completely different graphs, this is worrying, and as such I feel a new direction with the programming is required. For the most up to date program see commit 342e52b
