### ISSUE TITLE
Roles selection

### ISSUE THREAD

**Issue by MahinGH** [TomCatanach/TheRichmondRyders#5]
Please comment on the role you want to take. read the WhatsApp discussion and come to a  decision. we need to fill up positions in, VERY BASIC.
- Documentation
- Testing 
- 2 roles for coding (input variables)
- 1 role for Laplacian differential (using either for loop or matrix)
- Producing the mp4 and plotting (later on).
- Error testing
- estimate the frequency of the oscillations and  produce a numerical solution to the particle in a well.

**Comment by LizBloomfield** [comment]
I'm confident on the plotting (later on) and I can give producing the mp4 a go!

**Comment by TomCatanach** [comment]
The laplacian has been started in commit 551cda0

**Comment by Katongakitkat** [comment]
Beginning work on the packaging code

**Comment by kna17** [comment]
I will attempt some work on the input variables

**Comment by LizBloomfield** [comment]
> 

Nice! could u possibly reply to this in the code for general plot issue too so that there isn't too much confusion :)

**Comment by AmritWalia13** [comment]
Written in main
